### ISSUE TITLE
Checkbox & Radio button styling suggestion

### ISSUE THREAD

**Issue by erangatl** [wso2-dev-ux/theme-wso2#26]
Shall we change checkbox and radio button styles to make it more prominent. 

![rdch](https://cloud.githubusercontent.com/assets/20179540/19263594/b3ff941c-8fba-11e6-9ef2-08a0149e1b71.jpg)

**Comment by jeradrutnam** [comment]
Please send a PR with the fix.

**Comment by jeradrutnam** [comment]
Commit: b40ebb9310c98a4161f064d145ed8c3f982ee588
